project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    background: primary
    left:
    - text: "🐻 Hands-on Exercise"
      menu:
      - text: "Hands-on Exercise 1"
        href: "Hands-on_Ex/Hands-on_Ex01/data/Hands-on Exercise 1.qmd"
      - text: "Hands-on Exercise 2"
        href: "Hands-on_Ex/Hands-on_Ex02/data/Hands-on_Exercise 2.qmd"
      - text: "Hands-on Exercise 3A"
        href: "Hands-on_Ex/Hands-on_Ex03/data/Hands-on_Exercise 3A.qmd"
      - text: "Hands-on Exercise 3B"
        href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Exercise 3B.qmd"
      - text: "Hands-on Exercise 4A"
        href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Exercise 4A.qmd"
      - text: "Hands-on Exercise 4B"
        href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Exercise 4B.qmd"
      - text: "Hands-on Exercise 4C"
        href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Exercise 4C.qmd"
      - text: "Hands-on Exercise 4D"
        href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Exercise 4D.qmd"
      - text: "Hands-on Exercise 5"
        href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Exercise 5.qmd"
      - text: "Hands-on Exercise 6"
        href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Exercise 6.qmd"
      - text: "Hands-on Exercise 7"
        href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Exercise 7.qmd"
      - text: "Hands-on Exercise 8_1"
        href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Exercise 8.qmd"
      - text: "Hands-on Exercise 8_2"
        href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Exercise 8_2.qmd"
      - text: "Hands-on Exercise 8_3"
        href: "Hands-on_Ex/Hands-on_Ex08/hands-on_Exercise 8_3.qmd"
    - text: "🐻 In-class Exercise"
      menu:
      - text: "In-class Exercise 5"
        href: "VAST Challenge 2025/MC1/VAST Challenge 2025.qmd"
    - text: " 🦊 Take-Home Exercise"
      menu:
      - text: "Take-Home Exercise 1"
        href: "Take-home_Exercise/Take-home_Ex01/Take-Home_Exercise01.qmd"
      - text: "Take-Home Exercise 1 - Part 2"
        href: "Take-home_Exercise/Take-home_Ex01/Take-Home_Exercise01-Part02.qmd"
      - text: "Take-Home Exercise 2"
        href: "Take-home_Exercise/Take-home_Ex02/Take-Home_Excercise02.qmd"
      - text: "Take-Home Exercise 3"
        href: "Take-home_Exercise/Take-home_Ex03/Take-Home_Exercise03.qmd"
    right: 
      - href: index.qmd
        text: Home
      - about.qmd 

format:
  html:
    theme: flatty
    css: styles.css
    toc: true

editor: visual
