---
title: "Investment Vis"
author: "patriciatrisno"
format: dashboard
execute: 
  echo: false
editor: visual
---

```{r}

pacman::p_load(tidyverse, tidyquant, timetk, plotly,glue)
```

```{r}

SGstock <- read_csv("data/SGStock.csv")
```

```{r}

daily_prices <- SGstock %>%
  select(Symbol) %>%
  tq_get (get = "stock.prices",
          from = "2025-01-01",
          to = Sys.Date())

daily_prices <- daily_prices %>%
  left_join(SGstock)
```

# DBS

```{r}

start_date <- min(daily_prices$date)
end_date <- max(daily_prices$date)
```

## Row {height=20%}

```{r}

daily_summary <- daily_prices %>%
  filter(Symbol == "D05.SI" &
           date == end_date)
```

```{r}
#| content: valuebox
#| title: "Opening Price"

list(color = "primary",
     value = daily_summary$open
)
```


```{r}
#| content: valuebox
#| title: "Closing Price"

list(color = "primary",
     value = daily_summary$close
)
```
```{r}
#| content: valuebox
#| title: "Daily high"

list(color = "primary",
     value = daily_summary$high
)
```


```{r}

df <- daily_prices %>%
  filter(Name == "DBS Group")

mean_close <- mean(df$close, na.rm = TRUE)
sd_close <- sd(df$close, na.rm = TRUE)
ucl <- mean_close +1 * sd_close
lcl <- mean_close -1 * sd_close

df <- df %>%
  mutate(Flag = case_when(
         close > ucl ~ "Above UCl",
         close < ucl ~ "below UCL",
         TRUE ~ "Within Limits"))
         

mean_lbl <- paste0("Mean: ", round(mean_close, 2))

ucl_lbl <- paste0("UCL: ", round(ucl, 2))
lcl_lbl <- paste0("UCL: ", round(lcl, 2))

start_lbl <- format(start_date, "%d %B %Y")
end_lbl <- format(end_date, "%d %B %Y")
start_lbl <- sub("^0", "", start_lbl)
end_lbl <- sub("^0", "", end_lbl)
dynamic_title <- glue("DBS Stock Prices from {start_lbl} to {end_lbl}")
```


# OCBC

# SingTel

# SIA

# CapitaLand Mall Trust
